### ISSUE TITLE
These images are huge

### ISSUE THREAD

**Issue by inmanturbo** [AntonioMeireles/ClearLinux-packer#24]
First I just want to say that is is great that someone is doing this. However when I pull this I end up with like a 40g volume (!).
I'm trying to set up a three node prototype for a kubernetes project on a small nested libvirt instance. I don't want to have to mount a san/nas volume with this instance as that will introduce some extras complexities regarding permissions that come along with using nfs for a libvirt pool that I don't want to bother with just for this little lab. And I don't want to put in another storage ticket. It shouldn't be necessary.

Anyway the thing crashes my vm and I had no idea why until I took a peak under the hood with virsh and saw this massive qcow2. Must the image be so large?

Thanks

**Comment by AntonioMeireles** [comment]
@inmanturbo 

hi! first things first - **thanks for finding my images useful** :-) 

box size ended being 40G for historical and consistency reasons - as it's the same size in the other variants for the remaining providers. 

I can trivially take a lower default and update docs to point users to `vagrant-livbirt`'s driver `machine_virtual_size` option which ([quoting](https://github.com/vagrant-libvirt/vagrant-libvirt#domain-specific-options)) ...
>  Sets the disk size in GB for the machine overriding the default specified in the box. Allows boxes to defined with a minimal size disk by default and to be grown to a larger size at creation time. Will ignore sizes smaller than the size specified by the box metadata. Note that **currently there is no support for automatically resizing the filesystem to take advantage of the larger disk.**

I'll take a look soonish at shrinking default size while at same time trying to transparently handle on my side the fs resize part which the `vagrant-livbirt`'s driver doesn't do, so that ends being fully transparent to the end user.

thanks again!

**Comment by inmanturbo** [comment]
Thank you! Yes very useful. I'm a big fan of the stateless design and Clear
Linux and  finding little gems like your project is very exciting and gives
me great hope (and ideas) for my future plans with the OS.

**Comment by AntonioMeireles** [comment]
@inmanturbo 

Hi, (sorry the lag) 

just committed the needed changes. Default size will be now 5G. if no issues arise in ongoing smoke testing this week images will already consume this changes.  

Many thanks for your patience!

**Comment by inmanturbo** [comment]
Thank you very much! Less overhead makes it much easier to spin up a bunch
of these. Size can always be increased when needed.

**Comment by AntonioMeireles** [comment]
@inmanturbo 

**just pushed `33650` boxes that consume this feature**. they also work smoothly with latest vagrant (2.2.10) which got less stateless friendly than before. 

Feel  free to reopen or fill a new bug if issues arise. 

Thanks, once again, for your patience!
